"""
Interactive test script to explore the music recommender system.

You can input user preferences and see:
- Semantic similarity scores for genre/mood
- Dynamic weights from the LLM
- Top-K recommendations with detailed reasoning
"""
# Suppress warnings at the start
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'
os.environ['TRANSFORMERS_VERBOSITY'] = 'error'

import warnings
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

# Suppress sentence-transformers logging
import logging
logging.getLogger('sentence_transformers').setLevel(logging.ERROR)
logging.getLogger('transformers').setLevel(logging.ERROR)
logging.getLogger('huggingface_hub').setLevel(logging.ERROR)

from src.recommender import (
    load_songs, Song, UserProfile, Recommender, 
    semantic_text_similarity, get_dynamic_weights
)



def display_semantic_test(genre: str, mood: str):
    """Show semantic similarity scores for user genre/mood against all songs."""
    songs_data = load_songs("data/songs.json")
    
    print(f"\n{'='*70}")
    print(f"SEMANTIC SIMILARITY TEST")
    print(f"{'='*70}")
    print(f"User preference: {genre.upper()} genre, {mood.upper()} mood\n")
    
    print(f"{'Song':<35} {'Genre Sim':<12} {'Mood Sim':<12}")
    print("-" * 70)
    
    for song in songs_data:
        genre_sim = semantic_text_similarity(song["genre"], genre)
        mood_sim = semantic_text_similarity(song["mood"], mood)
        print(f"{song['title']:<35} {genre_sim:.3f}         {mood_sim:.3f}")
    
    print("\n✓ Semantic similarity working: 1.0 = perfect match, 0.0 = no match")
    print("  Example: 'pop' vs 'indie-pop' should score > 0.5, not just 0 or 1")


def display_dynamic_weights(genre: str, mood: str, energy: float, sample_song_idx: int = 0):
    """Show dynamic weights generated by the LLM for a sample song."""
    songs_data = load_songs("data/songs.json")
    
    if sample_song_idx >= len(songs_data):
        sample_song_idx = 0
    
    song = songs_data[sample_song_idx]
    user_prefs = {
        "genre": genre,
        "mood": mood,
        "energy": energy,
        "tempo_bpm": 100,  # default
    }
    
    print(f"\n{'='*70}")
    print(f"DYNAMIC WEIGHT AGENT TEST")
    print(f"{'='*70}")
    print(f"User profile: {mood.upper()} mood, {genre.upper()} genre, energy {energy:.1f}")
    print(f"Sample song: '{song['title']}' - {song['vibe_description']}\n")
    
    weights = get_dynamic_weights(user_prefs, song)
    print(f"Weights generated by LLM (or defaults if API unavailable):")
    print(f"  Genre:  {weights['genre']:.3f}")
    print(f"  Mood:   {weights['mood']:.3f}")
    print(f"  Energy: {weights['energy']:.3f}")
    print(f"  Tempo:  {weights['tempo']:.3f}")
    print(f"  Total:  {sum(weights.values()):.3f}")
    
    if sum(weights.values()) == 1.0:
        print("\n✓ Weights sum to 1.0 (valid)")
    else:
        print(f"\n⚠ Weights don't sum to 1.0 (normalized: {sum(weights.values()):.3f})")


def interactive_recommendation():
    """Interactive mode: Input preferences and get recommendations."""
    print(f"\n{'='*70}")
    print("INTERACTIVE RECOMMENDATION TEST")
    print(f"{'='*70}\n")
    
    # Load songs and convert to Song objects
    songs_data = load_songs("data/songs.json")
    songs_objs = [
        Song(
            id=s["id"],
            title=s["title"],
            artist=s["artist"],
            genre=s["genre"],
            mood=s["mood"],
            energy=s["energy"],
            tempo_bpm=s["tempo_bpm"],
            valence=s["valence"],
            danceability=s["danceability"],
            acousticness=s["acousticness"],
            vibe_description=s["vibe_description"],
        )
        for s in songs_data
    ]
    
    # Get user input
    print("Enter your music preferences:")
    genre = input("  Favorite genre (e.g., pop, lofi, rock): ").strip().lower()
    mood = input("  Favorite mood (e.g., happy, chill, intense): ").strip().lower()
    
    try:
        energy = float(input("  Target energy (0.0 to 1.0): ").strip())
        energy = max(0.0, min(1.0, energy))
    except ValueError:
        energy = 0.5
        print(f"  (Invalid input, using default: {energy})")
    
    # Create user profile
    user = UserProfile(
        favorite_genre=genre,
        favorite_mood=mood,
        target_energy=energy,
        likes_acoustic=False,
    )
    
    # Get recommendations
    recommender = Recommender(songs_objs)
    k = 5
    
    # Debug: Check if API key is loaded
    from dotenv import load_dotenv
    load_dotenv()
    import os
    api_key = os.getenv("OPENAI_API_KEY", "")
    if api_key:
        print(f"\n✓ API Key loaded: {api_key[:20]}...")
    else:
        print("\n⚠ No API key found. Using default weights.")
    
    # Show reasoning
    reasoning = recommender.explain_top_k_reasoning(user, k=k)
    print(reasoning)
    
    print("\n" + "="*70)
    print("INTERPRETATION GUIDE")
    print("="*70)
    print("• Score: Weighted sum of all similarities (0-1)")
    print("• Semantic similarity: Text embeddings (pop vs indie-pop = ~0.8, not 0)")
    print("• Dynamic weights: Should vary per song; if all same, LLM call failed")
    print("• Advantage: Score difference showing why one song ranks higher")


def main():
    """Main menu for testing."""
    while True:
        print("\n" + "="*70)
        print("MUSIC RECOMMENDER INTERACTIVE TEST")
        print("="*70)
        print("\n1. Test semantic similarity (genre/mood matching)")
        print("2. Test dynamic weight agent (LLM-generated weights)")
        print("3. Interactive recommendation (input your preferences)")
        print("4. Exit\n")
        
        choice = input("Select an option (1-4): ").strip()
        
        if choice == "1":
            genre = input("Enter genre (e.g., pop, lofi, rock): ").strip().lower()
            mood = input("Enter mood (e.g., happy, chill, intense): ").strip().lower()
            if genre and mood:
                display_semantic_test(genre, mood)
            else:
                print("⚠ Invalid input")
        
        elif choice == "2":
            genre = input("Enter genre: ").strip().lower()
            mood = input("Enter mood: ").strip().lower()
            try:
                energy = float(input("Enter energy (0-1): ").strip())
            except ValueError:
                energy = 0.5
            if genre and mood:
                display_dynamic_weights(genre, mood, energy)
            else:
                print("⚠ Invalid input")
        
        elif choice == "3":
            interactive_recommendation()
        
        elif choice == "4":
            print("\nGoodbye!")
            break
        
        else:
            print("⚠ Invalid choice")


if __name__ == "__main__":
    main()
