"""
Interactive test script to explore the music recommender system.

You can input user preferences and see:
- Semantic similarity scores for genre/mood
- Dynamic weights from the LLM
- Top-K recommendations with detailed reasoning
"""
# Suppress warnings at the start
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'
os.environ['TRANSFORMERS_VERBOSITY'] = 'error'

import warnings
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

# Suppress sentence-transformers logging
import logging
logging.getLogger('sentence_transformers').setLevel(logging.ERROR)
logging.getLogger('transformers').setLevel(logging.ERROR)
logging.getLogger('huggingface_hub').setLevel(logging.ERROR)

from src.recommender import (
    load_songs, Song, UserProfile, Recommender,
    semantic_text_similarity, get_dynamic_weights
)


def get_catalog_values():
    """Return the sets of unique genres and moods from the catalog."""
    songs_data = load_songs("data/songs.json")
    genres = sorted({s["genre"].lower() for s in songs_data})
    moods = sorted({s["mood"].lower() for s in songs_data})
    return genres, moods


def validate_input(user_input: str, known_values: list, field: str) -> str:
    """
    Validate a genre or mood input against known catalog values.

    - Exact match  → accepted silently.
    - Close match (sim ≥ 0.65) → suggests the nearest value; user can swap or keep.
    - Weak match   (sim < 0.40) → warns that results will likely be poor and
                                   prints the full list of known values.
    Returns the (possibly corrected) input string.
    """
    lower = user_input.strip().lower()

    if not lower:
        print(f"  ✗ {field.capitalize()} cannot be empty.")
        return lower

    # Exact match — nothing to do
    if lower in known_values:
        return lower

    # Find closest match by semantic similarity
    best_match = None
    best_score = 0.0
    for val in known_values:
        score = semantic_text_similarity(lower, val)
        if score > best_score:
            best_score = score
            best_match = val

    if best_score >= 0.65:
        print(f"  ⚠ '{user_input}' is not in the catalog.")
        print(f"    Closest {field}: '{best_match}' (similarity {best_score:.2f})")
        swap = input(f"    Use '{best_match}' instead? (y/n): ").strip().lower()
        if swap == "y":
            print(f"    ✓ Using '{best_match}'.")
            return best_match
        else:
            print(f"    Continuing with '{lower}' — scores may be lower than expected.")
    elif best_score >= 0.40:
        print(f"  ⚠ '{user_input}' is not a recognized {field} "
              f"(closest: '{best_match}', similarity {best_score:.2f}).")
        print(f"    Recommendations may be less reliable.")
    else:
        print(f"  ✗ '{user_input}' does not match any known {field} in the catalog.")
        print(f"    Known {field}s: {', '.join(known_values)}")
        print(f"    Continuing anyway — recommendations will likely be poor.")

    return lower


def display_semantic_test(genre: str, mood: str):
    """Show semantic similarity scores for user genre/mood against all songs."""
    songs_data = load_songs("data/songs.json")

    print(f"\n{'='*70}")
    print(f"SEMANTIC SIMILARITY TEST")
    print(f"{'='*70}")
    print(f"User preference: {genre.upper()} genre, {mood.upper()} mood\n")

    print(f"{'Song':<35} {'Genre Sim':<12} {'Mood Sim':<12}")
    print("-" * 70)

    for song in songs_data:
        genre_sim = semantic_text_similarity(song["genre"], genre)
        mood_sim = semantic_text_similarity(song["mood"], mood)
        print(f"{song['title']:<35} {genre_sim:.3f}         {mood_sim:.3f}")

    print("\n✓ Semantic similarity working: 1.0 = perfect match, 0.0 = no match")
    print("  Example: 'pop' vs 'indie-pop' should score > 0.5, not just 0 or 1")


def display_dynamic_weights(genre: str, mood: str, energy: float, sample_song_idx: int = 0):
    """Show dynamic weights generated by the LLM for a sample song."""
    songs_data = load_songs("data/songs.json")

    if sample_song_idx >= len(songs_data):
        sample_song_idx = 0

    song = songs_data[sample_song_idx]
    user_prefs = {
        "genre": genre,
        "mood": mood,
        "energy": energy,
        "tempo_bpm": 100,
    }

    print(f"\n{'='*70}")
    print(f"DYNAMIC WEIGHT AGENT TEST")
    print(f"{'='*70}")
    print(f"User profile: {mood.upper()} mood, {genre.upper()} genre, energy {energy:.1f}")
    print(f"Sample song: '{song['title']}' - {song['vibe_description']}\n")

    weights = get_dynamic_weights(user_prefs, song)
    print(f"Weights generated by LLM (or defaults if API unavailable):")
    print(f"  Genre:  {weights['genre']:.3f}")
    print(f"  Mood:   {weights['mood']:.3f}")
    print(f"  Energy: {weights['energy']:.3f}")
    print(f"  Tempo:  {weights['tempo']:.3f}")
    print(f"  Total:  {sum(weights.values()):.3f}")

    if sum(weights.values()) == 1.0:
        print("\n✓ Weights sum to 1.0 (valid)")
    else:
        print(f"\n⚠ Weights don't sum to 1.0 (normalized: {sum(weights.values()):.3f})")


def interactive_recommendation():
    """Interactive mode: Input preferences and get recommendations."""
    print(f"\n{'='*70}")
    print("INTERACTIVE RECOMMENDATION TEST")
    print(f"{'='*70}\n")

    songs_data = load_songs("data/songs.json")
    known_genres, known_moods = get_catalog_values()

    songs_objs = [
        Song(
            id=s["id"],
            title=s["title"],
            artist=s["artist"],
            genre=s["genre"],
            mood=s["mood"],
            energy=s["energy"],
            tempo_bpm=s["tempo_bpm"],
            valence=s["valence"],
            danceability=s["danceability"],
            acousticness=s["acousticness"],
            vibe_description=s["vibe_description"],
        )
        for s in songs_data
    ]

    print("Enter your music preferences:")
    raw_genre = input("  Favorite genre (e.g., pop, lofi, rock): ")
    genre = validate_input(raw_genre, known_genres, "genre")

    raw_mood = input("  Favorite mood (e.g., happy, chill, intense): ")
    mood = validate_input(raw_mood, known_moods, "mood")

    try:
        energy = float(input("  Target energy (0.0 to 1.0): ").strip())
        energy = max(0.0, min(1.0, energy))
    except ValueError:
        energy = 0.5
        print(f"  (Invalid input, using default: {energy})")

    user = UserProfile(
        favorite_genre=genre,
        favorite_mood=mood,
        target_energy=energy,
        likes_acoustic=False,
    )

    recommender = Recommender(songs_objs)
    k = 5

    from dotenv import load_dotenv
    load_dotenv()
    api_key = os.getenv("OPENAI_API_KEY", "")
    if not api_key:
        print("\n⚠ No API key found. Using default weights.")

    reasoning = recommender.explain_top_k_reasoning(user, k=k)
    print(reasoning)

    print("\n" + "="*70)
    print("INTERPRETATION GUIDE")
    print("="*70)
    print("• Score: Weighted sum of all similarities (0-1)")
    print("• Semantic similarity: Text embeddings (pop vs indie-pop = ~0.8, not 0)")
    print("• Dynamic weights: Should vary per song; if all same, LLM call failed")
    print("• Advantage: Score difference showing why one song ranks higher")


def main():
    """Main menu for testing."""
    known_genres, known_moods = get_catalog_values()

    while True:
        print("\n" + "="*70)
        print("MUSIC RECOMMENDER INTERACTIVE TEST")
        print("="*70)
        print("\n1. Test semantic similarity (genre/mood matching)")
        print("2. Test dynamic weight agent (LLM-generated weights)")
        print("3. Interactive recommendation (input your preferences)")
        print("4. Exit\n")

        choice = input("Select an option (1-4): ").strip()

        if choice == "1":
            raw_genre = input("Enter genre (e.g., pop, lofi, rock): ")
            raw_mood = input("Enter mood (e.g., happy, chill, intense): ")
            genre = validate_input(raw_genre, known_genres, "genre")
            mood = validate_input(raw_mood, known_moods, "mood")
            if genre and mood:
                display_semantic_test(genre, mood)
            else:
                print("⚠ Invalid input")

        elif choice == "2":
            raw_genre = input("Enter genre: ")
            raw_mood = input("Enter mood: ")
            genre = validate_input(raw_genre, known_genres, "genre")
            mood = validate_input(raw_mood, known_moods, "mood")
            try:
                energy = float(input("Enter energy (0-1): ").strip())
            except ValueError:
                energy = 0.5
            if genre and mood:
                display_dynamic_weights(genre, mood, energy)
            else:
                print("⚠ Invalid input")

        elif choice == "3":
            interactive_recommendation()

        elif choice == "4":
            print("\nGoodbye!")
            break

        else:
            print("⚠ Invalid choice")


if __name__ == "__main__":
    main()
